# -*- mode: yaml -*-
# # Hadolint config file
# # https://hadolint.github.io/hadolint/

# Failure mode
failure-threshold: none
no-fail: false

# Output format
format: tty
no-color: true

ignored:
  - DL3006 # warning: Always tag the version of an image explicitly
  - DL3008 # warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
  - DL3018 # warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>
