---
name: Lint Dockerfiles

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile*'

jobs:
  lint-dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint the Dockerfiles
        run: |
          make lint-all
